# Site settings
title: ClojureBridge Berlin Curriculum
email: clojurebridge.berlin@gmail.com
baseurl: /curriculum
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "http://clojurebridge-berlin.github.io/"
twitter_username: ClojureBridgeDE
github_username:  ClojureBridgeDE

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable : true
encoding: UTF-8
exclude:
- Gemfile
- Gemfile.lock
- CONTRIBUTING.md
- EDITING-CURRICULUM.md
- ClojurebridgeCheatsheet-v2.pdf
- TEACHING.md
- tmp

# Port number
port: 5555
